# Generated by Django 2.2.5 on 2022-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategoty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '图片类型',
                'verbose_name_plural': '图片类型',
                'db_table': 'vgpic_ImageCategoly',
            },
        ),
    ]
