# Generated by Django 2.2.5 on 2022-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.CharField(default='https://img.afqaq.com/images/2022/04/18/log.gif', max_length=1024, verbose_name='pic link'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_thumbnail',
            field=models.CharField(default='https://img.afqaq.com/images/2022/04/18/log.gif', max_length=1024, verbose_name='pic thumbnail'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_title',
            field=models.CharField(default='VanGogh', max_length=8, verbose_name='pic name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category_id',
            field=models.CharField(max_length=100, verbose_name='category id'),
        ),
    ]
