# Generated by Django 2.2.5 on 2022-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0003_auto_20220417_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category_id',
            field=models.IntegerField(verbose_name='category id'),
        ),
    ]
