# Generated by Django 2.2.5 on 2022-04-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8, verbose_name='画册标题')),
                ('stars', models.IntegerField(verbose_name='收藏数量')),
                ('comments', models.IntegerField(verbose_name='评论数量')),
                ('expostitory', models.TextField(verbose_name='画册简介')),
                ('created_time', models.DateField(verbose_name='画册创建时间')),
                ('img_list', models.TextField(verbose_name='画册中图片的ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者的ID')),
            ],
            options={
                'verbose_name': '画册',
                'verbose_name_plural': '画册',
                'db_table': 'vgpic_albums',
            },
        ),
    ]
