# Generated by Django 2.2.5 on 2022-04-16 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLike', models.BooleanField(verbose_name='画册ID')),
                ('albums_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums', verbose_name='画册ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户画册中间表',
                'verbose_name_plural': '用户画册中间表',
                'db_table': 'vgpic_UserAlbum',
            },
        ),
    ]
