# Generated by Django 2.2.5 on 2022-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_useralbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='cover_img',
            field=models.CharField(default='https://img.afqaq.com/images/2022/04/18/sky1.jpg', max_length=100, verbose_name='Pic defaltimg'),
        ),
    ]
