# Generated by Django 2.2.5 on 2022-05-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20220424_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='album_type',
            field=models.CharField(default='名画', max_length=8, verbose_name='画册类型'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='albums_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='画册ID'),
        ),
    ]
