# Generated by Django 2.2.5 on 2022-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_img',
            field=models.ImageField(default='https://img.afqaq.com/images/2022/04/18/i.jpg', null=True, upload_to='img/'),
        ),
    ]
